### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by aniketh-g** [aupasana/amara-quiz#33]
Verse 1.1.10.2 reads **मा**हाराजिकसाध्याश्च instead of **म**हाराजिकसाध्याश्च 
Verse 1.1.35.4 reads वारीही instead of वाराही

**Comment by aupasana** [comment]
Fixed with the following commit. Will need a redeployment to be seen on the website.

https://github.com/aupasana/amara-quiz/commit/75f306df91608ba0614d32d7a9725eb3c79d0a3e
